# Generated by Django 3.1.8 on 2021-07-29 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='Your description goes here!')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2021, 7, 29, 21, 46, 30, 599945, tzinfo=utc))),
                ('expiry_date', models.DateTimeField(default=datetime.datetime(2021, 8, 5, 21, 46, 30, 599945, tzinfo=utc))),
            ],
        ),
    ]
