# Generated by Django 3.1.8 on 2021-07-29 21:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 29, 21, 49, 37, 850791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 5, 21, 49, 37, 850791, tzinfo=utc)),
        ),
    ]
